#!/usr/bin/env python3

import argparse, re

parser = argparse.ArgumentParser(description = 'fixTab')
parser.add_argument('input', action = 'store', type = str, help = 'input file')
parser.add_argument('output', action = 'store', type = str, help = 'output file')
parser.add_argument('-i', '--insep', action = 'store', type = str, default = '\s+', help = 'input file separator')
parser.add_argument('-o', '--outsep', action = 'store', type = str, default = '\t', help = 'output file separator')
parser.add_argument('-d', '--dstrip', action = 'store_true', help = 'disable strip')
parser.add_argument('-r', '--rheader', action = 'store_true', help = 'remove header')
parser.add_argument('-b', '--bheader', action = 'store', type = str, default = '#', help = 'first character of header')
args = parser.parse_args()

def write_converted_line(line, o):
    if all([args.rheader, line[0] == args.bheader]): return
    if not args.dstrip: line = line.strip()
    line = re.sub(args.insep, args.outsep, line)
    if not line[-1] == '\n': line += '\n'
    o.write(line)
    o.flush()

i = open(args.input, 'rt')
o = open(args.output, 'wt')

[write_converted_line(line, o) for line in i.readlines()]

i.close()
o.close()
